services:
  streamlit:
    build:
      context: ..
      dockerfile: Etl/Dockerfile
    image: n4ssim11/clinique-plus:streamlit
    container_name: clinique-streamlit
    ports:
      - "8501:8501" # resultats nuits + IA comorbidites
      - "8502:8502" # dashboard CPAP
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      API_BASE_URL: http://api:3000
      ANGULAR_BASE_URL: http://localhost:8080
    volumes:
      - ./outputs:/app/Etl/outputs
      - ../base_analytique.db:/app/base_analytique.db
      - ../models:/app/models
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
