services:
  api:
    build:
      context: ..
      dockerfile: Api/Dockerfile
    image: node-application
    container_name: clinique-api
    ports:
      - "9000:3000"
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy